/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
import AsyncStorage from '@react-native-async-storage/async-storage';

// Generated by `yarn storybook-generate` (run automatically before `start`/`ios`/`android`).
// Registers every story matched by the glob in `main.ts`, calls `start(...)` itself, and
// exports the resulting `view` — @storybook/react-native@7's package root does NOT export a
// `getStorybookUI` factory (that was the v6 API); the UI is obtained by calling
// `view.getStorybookUI(...)` on the View instance `start()` returns. Re-run the generate
// script after adding or removing a `.story.tsx` file — Metro can't discover them dynamically.
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  asyncStorage: AsyncStorage,
});

export default StorybookUIRoot;
